// Media list. build.py swaps paths for embedded data in the one-file version.
window.ASSETS = {
  audio: {
    a_letter: "assets/audio/a_letter.mp3",
    a_moonlady: "assets/audio/a_moonlady.mp3",
    a_sound: "assets/audio/a_sound.mp3",
    all_clean: "assets/audio/all_clean.mp3",
    bath_time: "assets/audio/bath_time.mp3",
    bed_time: "assets/audio/bed_time.mp3",
    bg_music: "assets/audio/bg_music.mp3",
    bye: "assets/audio/bye.mp3",
    care_hi: "assets/audio/care_hi.mp3",
    done: "assets/audio/done.mp3",
    dress_up: "assets/audio/dress_up.mp3",
    drink_milk: "assets/audio/drink_milk.mp3",
    eat_apple: "assets/audio/eat_apple.mp3",
    eat_banana: "assets/audio/eat_banana.mp3",
    eat_carrot: "assets/audio/eat_carrot.mp3",
    eat_cookie: "assets/audio/eat_cookie.mp3",
    eat_mooncake: "assets/audio/eat_mooncake.mp3",
    find_backpack: "assets/audio/find_backpack.mp3",
    find_book: "assets/audio/find_book.mp3",
    find_chair: "assets/audio/find_chair.mp3",
    find_crayon: "assets/audio/find_crayon.mp3",
    find_gluestick: "assets/audio/find_gluestick.mp3",
    find_lantern: "assets/audio/find_lantern.mp3",
    find_moon: "assets/audio/find_moon.mp3",
    find_mooncake: "assets/audio/find_mooncake.mp3",
    find_moonlady: "assets/audio/find_moonlady.mp3",
    find_pencil: "assets/audio/find_pencil.mp3",
    find_rabbit: "assets/audio/find_rabbit.mp3",
    find_same: "assets/audio/find_same.mp3",
    find_school: "assets/audio/find_school.mp3",
    find_scissors: "assets/audio/find_scissors.mp3",
    find_shadow: "assets/audio/find_shadow.mp3",
    find_snake: "assets/audio/find_snake.mp3",
    find_table: "assets/audio/find_table.mp3",
    full: "assets/audio/full.mp3",
    giggle: "assets/audio/giggle.mp3",
    go_school: "assets/audio/go_school.mp3",
    good_morning: "assets/audio/good_morning.mp3",
    good_night: "assets/audio/good_night.mp3",
    have_backpack: "assets/audio/have_backpack.mp3",
    have_book: "assets/audio/have_book.mp3",
    have_crayon: "assets/audio/have_crayon.mp3",
    have_gluestick: "assets/audio/have_gluestick.mp3",
    have_pencil: "assets/audio/have_pencil.mp3",
    have_scissors: "assets/audio/have_scissors.mp3",
    hello_ready: "assets/audio/hello_ready.mp3",
    hooray: "assets/audio/hooray.mp3",
    hungry: "assets/audio/hungry.mp3",
    itis_lantern: "assets/audio/itis_lantern.mp3",
    itis_moon: "assets/audio/itis_moon.mp3",
    itis_mooncake: "assets/audio/itis_mooncake.mp3",
    itis_rabbit: "assets/audio/itis_rabbit.mp3",
    lets_play: "assets/audio/lets_play.mp3",
    light_lanterns: "assets/audio/light_lanterns.mp3",
    listen: "assets/audio/listen.mp3",
    locked: "assets/audio/locked.mp3",
    look_great: "assets/audio/look_great.mp3",
    mid_happy: "assets/audio/mid_happy.mp3",
    no1: "assets/audio/no1.mp3",
    ok1: "assets/audio/ok1.mp3",
    ok2: "assets/audio/ok2.mp3",
    ok3: "assets/audio/ok3.mp3",
    pack_bag: "assets/audio/pack_bag.mp3",
    peekaboo: "assets/audio/peekaboo.mp3",
    pick_friend: "assets/audio/pick_friend.mp3",
    pop_bubbles: "assets/audio/pop_bubbles.mp3",
    put_backpack: "assets/audio/put_backpack.mp3",
    put_book: "assets/audio/put_book.mp3",
    put_crayon: "assets/audio/put_crayon.mp3",
    put_crown: "assets/audio/put_crown.mp3",
    put_gluestick: "assets/audio/put_gluestick.mp3",
    put_hat: "assets/audio/put_hat.mp3",
    put_pencil: "assets/audio/put_pencil.mp3",
    put_scissors: "assets/audio/put_scissors.mp3",
    put_shirt: "assets/audio/put_shirt.mp3",
    put_shoes: "assets/audio/put_shoes.mp3",
    put_socks: "assets/audio/put_socks.mp3",
    put_sunglasses: "assets/audio/put_sunglasses.mp3",
    q_have: "assets/audio/q_have.mp3",
    q_letter: "assets/audio/q_letter.mp3",
    q_sound: "assets/audio/q_sound.mp3",
    q_this: "assets/audio/q_this.mp3",
    q_whatisit: "assets/audio/q_whatisit.mp3",
    q_who: "assets/audio/q_who.mp3",
    s_hiss: "assets/audio/s_hiss.mp3",
    sticker: "assets/audio/sticker.mp3",
    tap_hear: "assets/audio/tap_hear.mp3",
    think: "assets/audio/think.mp3",
    this_backpack: "assets/audio/this_backpack.mp3",
    this_book: "assets/audio/this_book.mp3",
    this_chair: "assets/audio/this_chair.mp3",
    this_crayon: "assets/audio/this_crayon.mp3",
    this_gluestick: "assets/audio/this_gluestick.mp3",
    this_pencil: "assets/audio/this_pencil.mp3",
    this_school: "assets/audio/this_school.mp3",
    this_scissors: "assets/audio/this_scissors.mp3",
    this_snake: "assets/audio/this_snake.mp3",
    this_table: "assets/audio/this_table.mp3",
    tidy_intro: "assets/audio/tidy_intro.mp3",
    use_pillow: "assets/audio/use_pillow.mp3",
    use_shower: "assets/audio/use_shower.mp3",
    use_soap: "assets/audio/use_soap.mp3",
    use_sponge: "assets/audio/use_sponge.mp3",
    use_teddy: "assets/audio/use_teddy.mp3",
    w_apple: "assets/audio/w_apple.mp3",
    w_backpack: "assets/audio/w_backpack.mp3",
    w_balloon: "assets/audio/w_balloon.mp3",
    w_banana: "assets/audio/w_banana.mp3",
    w_bear: "assets/audio/w_bear.mp3",
    w_book: "assets/audio/w_book.mp3",
    w_bunny: "assets/audio/w_bunny.mp3",
    w_carrot: "assets/audio/w_carrot.mp3",
    w_cat: "assets/audio/w_cat.mp3",
    w_chair: "assets/audio/w_chair.mp3",
    w_cookie: "assets/audio/w_cookie.mp3",
    w_crayon: "assets/audio/w_crayon.mp3",
    w_crown: "assets/audio/w_crown.mp3",
    w_gluestick: "assets/audio/w_gluestick.mp3",
    w_hat: "assets/audio/w_hat.mp3",
    w_heart: "assets/audio/w_heart.mp3",
    w_lantern: "assets/audio/w_lantern.mp3",
    w_milk: "assets/audio/w_milk.mp3",
    w_moon: "assets/audio/w_moon.mp3",
    w_mooncake: "assets/audio/w_mooncake.mp3",
    w_moonlady: "assets/audio/w_moonlady.mp3",
    w_pencil: "assets/audio/w_pencil.mp3",
    w_pillow: "assets/audio/w_pillow.mp3",
    w_rabbit: "assets/audio/w_rabbit.mp3",
    w_rainbow: "assets/audio/w_rainbow.mp3",
    w_school: "assets/audio/w_school.mp3",
    w_scissors: "assets/audio/w_scissors.mp3",
    w_shirt: "assets/audio/w_shirt.mp3",
    w_shoes: "assets/audio/w_shoes.mp3",
    w_shower: "assets/audio/w_shower.mp3",
    w_snake: "assets/audio/w_snake.mp3",
    w_soap: "assets/audio/w_soap.mp3",
    w_socks: "assets/audio/w_socks.mp3",
    w_sponge: "assets/audio/w_sponge.mp3",
    w_sun: "assets/audio/w_sun.mp3",
    w_sunglasses: "assets/audio/w_sunglasses.mp3",
    w_table: "assets/audio/w_table.mp3",
    w_teddy: "assets/audio/w_teddy.mp3",
    w_tidyup: "assets/audio/w_tidyup.mp3",
    welcome_back: "assets/audio/welcome_back.mp3",
    what_play: "assets/audio/what_play.mp3",
    yay: "assets/audio/yay.mp3",
    yummy: "assets/audio/yummy.mp3"
  },
  img: {
    backpack: "assets/images/backpack.webp",
    book: "assets/images/book.webp",
    chair: "assets/images/chair.webp",
    crayon: "assets/images/crayon.webp",
    e_apple: "assets/images/e_apple.webp",
    e_balloon: "assets/images/e_balloon.webp",
    e_banana: "assets/images/e_banana.webp",
    e_bathtub: "assets/images/e_bathtub.webp",
    e_bed: "assets/images/e_bed.webp",
    e_bubbles: "assets/images/e_bubbles.webp",
    e_carrot: "assets/images/e_carrot.webp",
    e_cookie: "assets/images/e_cookie.webp",
    e_crescent: "assets/images/e_crescent.webp",
    e_crown: "assets/images/e_crown.webp",
    e_droplet: "assets/images/e_droplet.webp",
    e_firework: "assets/images/e_firework.webp",
    e_flower: "assets/images/e_flower.webp",
    e_fullmoon: "assets/images/e_fullmoon.webp",
    e_gift: "assets/images/e_gift.webp",
    e_glowstar: "assets/images/e_glowstar.webp",
    e_hat: "assets/images/e_hat.webp",
    e_heart: "assets/images/e_heart.webp",
    e_lollipop: "assets/images/e_lollipop.webp",
    e_milk: "assets/images/e_milk.webp",
    e_music: "assets/images/e_music.webp",
    e_party: "assets/images/e_party.webp",
    e_rainbow: "assets/images/e_rainbow.webp",
    e_redlantern: "assets/images/e_redlantern.webp",
    e_shirt: "assets/images/e_shirt.webp",
    e_shoes: "assets/images/e_shoes.webp",
    e_shower: "assets/images/e_shower.webp",
    e_soap: "assets/images/e_soap.webp",
    e_socks: "assets/images/e_socks.webp",
    e_sparkles: "assets/images/e_sparkles.webp",
    e_sponge: "assets/images/e_sponge.webp",
    e_star: "assets/images/e_star.webp",
    e_sun: "assets/images/e_sun.webp",
    e_sunglasses: "assets/images/e_sunglasses.webp",
    e_teddy: "assets/images/e_teddy.webp",
    e_thought: "assets/images/e_thought.webp",
    e_zzz: "assets/images/e_zzz.webp",
    gluestick: "assets/images/gluestick.webp",
    lantern: "assets/images/lantern.webp",
    lanternbunny: "assets/images/lanternbunny.webp",
    logo: "assets/images/logo.webp",
    moon: "assets/images/moon.webp",
    mooncake: "assets/images/mooncake.webp",
    moonlady: "assets/images/moonlady.webp",
    moonrabbits: "assets/images/moonrabbits.webp",
    pencil: "assets/images/pencil.webp",
    rabbit: "assets/images/rabbit.webp",
    school: "assets/images/school.webp",
    scissors: "assets/images/scissors.webp",
    snake: "assets/images/snake.webp",
    table: "assets/images/table.webp",
    tidyup: "assets/images/tidyup.webp"
  }
};
// Text of every voice line (used if a sound can't play)
window.VOICE_TEXT = {
"w_school": "School.",
"find_school": "Find the school.",
"w_scissors": "Scissors.",
"find_scissors": "Find the scissors.",
"w_snake": "Snake.",
"find_snake": "Find the snake.",
"w_backpack": "Backpack.",
"find_backpack": "Find the backpack.",
"w_book": "Book.",
"find_book": "Find the book.",
"w_chair": "Chair.",
"find_chair": "Find the chair.",
"w_crayon": "Crayon.",
"find_crayon": "Find the crayon.",
"w_gluestick": "Glue stick.",
"find_gluestick": "Find the glue stick.",
"w_pencil": "Pencil.",
"find_pencil": "Find the pencil.",
"w_table": "Table.",
"find_table": "Find the table.",
"w_moon": "Moon.",
"find_moon": "Find the moon.",
"w_mooncake": "Moon cake.",
"find_mooncake": "Find the moon cake.",
"w_lantern": "Lantern.",
"find_lantern": "Find the lantern.",
"w_moonlady": "Moon lady.",
"find_moonlady": "Find the moon lady.",
"w_rabbit": "Rabbit.",
"find_rabbit": "Find the rabbit.",
"this_school": "This is a school.",
"this_scissors": "These are scissors.",
"this_snake": "This is a snake.",
"this_backpack": "This is a backpack.",
"this_book": "This is a book.",
"this_chair": "This is a chair.",
"this_crayon": "This is a crayon.",
"this_gluestick": "This is a glue stick.",
"this_pencil": "This is a pencil.",
"this_table": "This is a table.",
"have_backpack": "I have a backpack.",
"put_backpack": "Put away the backpack.",
"have_book": "I have a book.",
"put_book": "Put away the book.",
"have_crayon": "I have a crayon.",
"put_crayon": "Put away the crayon.",
"have_gluestick": "I have a glue stick.",
"put_gluestick": "Put away the glue stick.",
"have_pencil": "I have a pencil.",
"put_pencil": "Put away the pencil.",
"have_scissors": "I have scissors.",
"put_scissors": "Put away the scissors.",
"itis_moon": "It's the moon.",
"itis_mooncake": "It's a moon cake.",
"itis_lantern": "It's a lantern.",
"itis_rabbit": "It's a rabbit.",
"q_whatisit": "What is it?",
"q_who": "Who is this?",
"a_moonlady": "Moon lady.",
"mid_happy": "Happy Mid-Autumn Festival!",
"light_lanterns": "Let's light the lanterns!",
"w_tidyup": "Tidy up!",
"q_letter": "What letter is it?",
"a_letter": "Letter S.",
"q_sound": "What sound is it?",
"a_sound": "Sound",
"q_this": "What is this?",
"q_have": "What do you have?",
"tidy_intro": "Let's tidy up!",
"ok1": "Great job!",
"ok2": "Well done!",
"ok3": "Super!",
"yay": "Yay!",
"hooray": "Hooray!",
"no1": "Oops! Try again.",
"think": "Hmm. Try again!",
"done": "All tidy! Good job!",
"listen": "Listen and find.",
"pop_bubbles": "Pop the bubbles!",
"peekaboo": "Peekaboo!",
"find_shadow": "Find the shadow!",
"find_same": "Find the same picture!",
"pack_bag": "Pack your backpack!",
"go_school": "Let's go to school!",
"sticker": "You got a sticker!",
"tap_hear": "Tap and listen!",
"hello_ready": "Hello! Are you ready?",
"lets_play": "Yes! Let's play!",
"bye": "Bye bye!",
"welcome_back": "Welcome back!",
"what_play": "What shall we play?",
"good_morning": "Good morning!",
"pick_friend": "Choose your friend!",
"care_hi": "Hi! I'm your friend.",
"giggle": "Hee hee!",
"w_bunny": "Bunny.",
"w_cat": "Cat. Meow!",
"w_bear": "Bear.",
"hungry": "I'm hungry!",
"yummy": "Yummy!",
"full": "I'm full! Thank you!",
"eat_apple": "Eat an apple.",
"eat_banana": "Eat a banana.",
"drink_milk": "Drink some milk.",
"eat_mooncake": "Eat a moon cake.",
"eat_carrot": "Eat a carrot.",
"eat_cookie": "Eat a cookie.",
"bath_time": "Bath time!",
"use_soap": "Soap. Bubbles, bubbles!",
"use_sponge": "Wash, wash, wash!",
"use_shower": "Water. Splash, splash!",
"all_clean": "All clean!",
"dress_up": "Let's get dressed!",
"put_shirt": "Put on your shirt.",
"put_shoes": "Put on your shoes.",
"put_hat": "Put on your hat.",
"put_socks": "Put on your socks.",
"put_sunglasses": "Put on your sunglasses.",
"put_crown": "Put on your crown.",
"look_great": "You look great!",
"bed_time": "Time for bed.",
"use_pillow": "Here is your pillow.",
"use_teddy": "Here is your teddy bear.",
"good_night": "Good night!",
"locked": "Get more stars to open it!",
"w_apple": "Apple.",
"w_banana": "Banana.",
"w_milk": "Milk.",
"w_carrot": "Carrot.",
"w_cookie": "Cookie.",
"w_soap": "Soap.",
"w_sponge": "Sponge.",
"w_shower": "Water.",
"w_shirt": "Shirt.",
"w_shoes": "Shoes.",
"w_hat": "Hat.",
"w_socks": "Socks.",
"w_sunglasses": "Sunglasses.",
"w_crown": "Crown.",
"w_pillow": "Pillow.",
"w_teddy": "Teddy bear.",
"w_heart": "Heart.",
"w_rainbow": "Rainbow.",
"w_balloon": "Balloon.",
"w_sun": "Sun.",
"s_hiss": "sss"
};
